@baseURL = http://localhost:4000/api/usuarios

###
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "Rafael Gomes",
    "email": "rafa@gmail.com",
    "senha": "Ab123!"
}

###
// POST - Efetuar o login
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "rafa@gmail.com",
    "senha": "Ab123!"
}

###
// GET - Obtem os usuários
GET {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU2MDdkZjkzODE5M2Y4ZTlhZGJjNDI1In0sImlhdCI6MTcwMDgyNTQzMywiZXhwIjoxNzAxMDg0NjMzfQ.vO5UdibBU0bFqJxcwYMf795_-L59mfu1Y8pvB8RBxNk

###
// DELETE - Remove usuário pelo id
DELETE {{baseURL}}/65607df938193f8e9adbc425
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU2MDdkZjkzODE5M2Y4ZTlhZGJjNDI1In0sImlhdCI6MTcwMDgyNTQzMywiZXhwIjoxNzAxMDg0NjMzfQ.vO5UdibBU0bFqJxcwYMf795_-L59mfu1Y8pvB8RBxNk

###
// PUT - Edita o usuário pelo id
PUT {{baseURL}}/65607df938193f8e9adbc425
Content-Type: application/json

{
    "nome": "Rafael Gomes",
    "email": "rafa@gmail.com",
    "senha": "Ab123!"
    "ativo": true
  }
